# This is necessary until https://github.com/travis-ci/travis-ci/issues/3120 is
# fixed
sudo: required

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2/cache
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
  - 2.11.8

jdk:
  - oraclejdk8

notifications:
  hipchat:
    rooms:
      secure: tcb+hO7CxqN2n8w38cejS4j7a30clWbwMCBxSsPBK4XyqCInCrw5RT+KPRwd+UtoNREgPmk7QeaeGTonEgW8g/1ArK2RTHTFsmMskAnIVjanTlVl3BKBl9gmHeU+nSeBp+yQb808/JkUq174M3hyoYAtHh7gEJ0eUpmry3JjuQg=

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS
  - ./bin/travisci
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION update

script: 
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success: 
  - bash <(curl -s https://codecov.io/bash)
